[config]
schemaVersion = "0.0.1"


[package]
namespace = "Jowday"
name = "BoonBuddy"
versionNumber = "0.6.11"
description = "Fully customizable boon rarity! Marks boons that were banned by Vow of Forsaking. Disables requirements for the Offerings button in the boon selection screen."
websiteUrl = "https://github.com/The-Black-Lodge/JowdayBoonBuddy"
containsNsfwContent = false

[package.dependencies]
SGG_Modding-ENVY = "1.0.0"
SGG_Modding-Chalk = "2.0.2"
SGG_Modding-ReLoad = "1.0.1"
SGG_Modding-ModUtil = "3.1.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", ]
